# disable all complexity and length limit for methods
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false # since we need long in-line shell commands

Style/NumericLiterals:
  MinDigits: 6 # so that port numbers won't be affected

# Personal preferences for styles

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
