# disable all complexity and length limit for methods
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Style/NumericLiterals:
  MinDigits: 6 # so that port numbers won't be affected

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false
